---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: grafana
  namespace: monitoring
spec:
  providerRef:
    name: grafana
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: 'apps'
      namespace: flux-system
---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: grafana
  namespace: monitoring
spec:
  type: grafana
  address: "http://grafana.monitoring.svc.cluster.local:3000/api/annotations"
  secretRef:
    name: grafana-auth
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-auth
  namespace: monitoring
stringData:
  token: "glsa_ey4Qwpc92lHmOkUbOayZLC6ftfqc5fAv_8145fd99"
